---
apiVersion: v1
kind: Namespace
metadata:
  name: budget-app
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: budget-app-mysql-database
  namespace: budget-app
spec:
  secretName: mysql-passwords
  tlsUseSelfSigned: true
  instances: 2
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-backend
  namespace: budget-app
  labels:
    app: budget-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-app-backend
  template:
    metadata:
      labels:
        app: budget-app-backend
    spec:
      containers:
        - name: budget-app-backend
          image: docker.io/library/budget-app:caleb
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-passwords
                  key: rootUser
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-passwords
                  key: rootPassword
            - name: HOST
              value: budget-app-mysql-database
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
