---
apiVersion: v1
kind: Namespace
metadata:
  name: budget-app
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: budget-app-mysql-database
  namespace: budget-app
spec:
  secretName: mysql-passwords
  tlsUseSelfSigned: true
  instances: 2
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-backend
  namespace: budget-app
  labels:
    app: budget-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-app-backend
  template:
    metadata:
      labels:
        app: budget-app-backend
        app.kubernetes.io/name: budget-app-backend
    spec:
      containers:
        - name: budget-app-backend
          image: 10.0.0.108:32000/budget-app:thomas-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: backend-http
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-passwords
                  key: rootUser
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-passwords
                  key: rootPassword
            - name: HOST
              value: budget-app-mysql-database
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: budget-app-backend-service
  namespace: budget-app
spec:
  selector:
    app.kubernetes.io/name: budget-app-backend
  ports:
    - name: backend-http-port
      protocol: TCP
      port: 8080
      targetPort: backend-http
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: budget-app-psql
  namespace: budget-app
spec:
  instances: 3
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
---
apiVersion: v1
kind: Secret
metadata:
  name: thomas-login
  namespace: budget-app
type: Opaque
data:
  username: dGhvbWFzCg==  # base64 encoded value of 'username'
  password: bXFuM3dlcSFqemFfQVFUN2JmdAo=  # base64 encoded value of 'password'