apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: budget-app-mysql-database
  namespace: budget-app
spec:
  secretName: mysql-passwords
  tlsUseSelfSigned: true
  instances: 2
  router:
    instances: 1